name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Set up Node.js (for potential SVG customization)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Add a custom header or logo to the SVG
      - name: Customize SVG with a header
        run: |
          echo "<!-- Custom Header -->" > dist/header.svg
          cat dist/github-contribution-grid-snake.svg >> dist/header.svg
          mv dist/header.svg dist/github-contribution-grid-snake.svg

      # push the content of <build_dir> to a branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Send notification on success
      - name: Send success notification
        if: success()
        run: |
          echo "🎉 The SVG animation was generated and pushed successfully!"

      # Notify if workflow fails
      - name: Send failure notification
        if: failure()
        run: |
          echo "🚨 The workflow failed, please check the logs for more details."
